version: "3"
services:
  gateway:
    image: workspace-gateway
    ports:
      - 8000:8000
    networks:
      - workspace
  service1:
    image: workspace-service1
    ports:
      - 8001:8001
    networks:
      - workspace
  service2:
    image: workspace-service2
    ports:
     - 8002:8002
    networks:
      - workspace

networks:
  workspace:
    driver: bridge